### PR TITLE
Reduced scope variable and fixed typos

### PR DESCRIPTION
**Pull request by jwillemsen**

### CODE REVIEW

**Comment by keestux** [comment]
Hi
I really appreciate the pull requests. However, in the case of SodaqCore-samd you have to realize that this is basically a fork of ArduinoCode-samd, plus
* variants for our own boards
* patches we deem important for our applications
With that i mind the "Fixed typo" commit is OK, but the change in wiring should preferably go through Arduino.

**Comment by jwillemsen** [comment]
The change in wiring.c has been merged already into the ArduinoCode-samd code base, looks in a branch the code was heavily modified, see PR #4, that is the fix that prevents the usage of -Werror. Why isn't this repo a real fork of ArduinoCode-samd with branches for your product? That way you can easily pull in changes from the main code, there has been a lot of changes there.

**Comment by keestux** [comment]
What makes you think it is not a real fork? It is.

**Comment by jwillemsen** [comment]
Because I didn't see below the project repo "forked from .." listed on github, maybe I just can't see it because I am not part of the organization? Good that it is a real fork.

**Comment by keestux** [comment]
Don't believe everything you see on Github :-)
I may have cloned it before creating the project on github. We've used bitbucket before and we have our own Gitlab server. There is a whole world outside Github :-)

**Comment by jwillemsen** [comment]
Closing, will make a new PR for just the typo

**Comment by jwillemsen** [comment]
Ok, the world outside of github probably explains a lot of things I noticed when looking at the various repositories ;-).

**Comment by jwillemsen** [comment]
FYI, the score of the variable was merged upstream as part of https://github.com/arduino/ArduinoCore-samd/pull/210

**Pull request closed without merging**
