### PR TITLE
Removed not used variable

### PR DESCRIPTION
**Pull request by jwillemsen**
* cores/arduino/wiring.c:

### CODE REVIEW

**Comment by jwillemsen** [comment]
Bit confused about the branches, would expect that autonomo is the main branch and that releases are purely a tag, let me know if you need this fix on another branch?

**Comment by jwillemsen** [comment]
Would appreciate it when there would be a new release, that way projects using sodaq/travis/platformio can enable -Werror

**Comment by keestux** [comment]
It is probably my fault that this confusion of the branches exist. The idea behind it was to create our (SODAQ) own branches so that we can add / modify our boards, and that we can fix things that we consider to be important. As soon as a branch was included in a release of a board manager JSON that branch was getting a tag, and the branch is closed for changes. The branches and tags have a -sodaq suffix to distinguish from the official Arduino branches and tags. (( Notice that because it is a clone of ArduinoCore-samd, and we continue to fetch from that, we have to be careful with the naming. ))

Recently (as in: yesterday), we are discussing a slightly different procedure. And that is to follow the tags from ArduinoCore-samd, and create our own branch from it with the -sodaq suffix. At least that should make it more obvious how the SodaqCore-samd version relates to the ArduinoCore-samd version.

**Comment by jwillemsen** [comment]
The challenge is with a branch based on a ArduinoCore-samd tag is that each time they add a tag in ArduinoCore-samd you have to add a branch and merge again changes. I haven't looked at all changes in details, but can't you use one branch forked from the ArduinoCore-samd master where you add your changes. At the moment the upstream ArduinoCore-samd has a new tag you can pull the changes to that tag into your branch. On your branch you can place sodaq_ tags to indicate your releases. I first assumed that you used this approach already with the autonomo branch.

**Comment by jwillemsen** [comment]
Let me know when you would need this change on another branch.

**Comment by jwillemsen** [comment]
@keestux Any plans to integrate this PR (and my others) so that we can enable -Werror on our code when using the sodaq boards on platformio?

**Comment by keestux** [comment]
We are struggling with the versioning.
1) we want to wait for ArduinoCore 1.6.13 and build our changes on top of that
2) we cannot just update the 1.6.12 tar.bz2 file (and the package JSON) because Arduino IDE gets confused about it. It will give checksum errors.
3) Arduino IDE cannot handle versions like 1.6.12.1

**Comment by jwillemsen** [comment]
@keestux Thanks for the update, hopefully this gets all released soon, enabling travis-ci greatly simplifies the testing of pull requests.

**Comment by jwillemsen** [comment]
@keestux Any plans to integrate the change to resolve the warning, Arduino 1.6.13 is available. Do have several other PRs standing ready for merge

**Comment by keestux** [comment]
Ah thanks for letting us know.
I've rebased our SODAQ changes onto ArduinoCore 1.6.13. See our new branch v1.6.13-sodaq
It's currently available from the "test" JSON at http://downloads.sodaq.net/test/package_test_sodaq_samd_index.json
I want to give it a brief time for people to test and then I'll place it in our official package JSON.

Notice that there is a ArduinoCore 1.6.14 already, which I will do shortly (coming days).

**Comment by jwillemsen** [comment]
Any plans to release 1.6.13 as new formal release soon?

**Pull request closed without merging**
